name: genpdf

on:
  workflow_dispatch:
  
  push:
    branches:
    - "*"

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache LaTeX packages
        uses: actions/cache@v2
        with:
          path: ~/.texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/texlive.packages') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-extra
          echo "texlive-latex-base\ntexlive-latex-recommended\ntexlive-fonts-extra" > texlive.packages
          
      - name: Run Makefile
        run: |
          make all clean
          
      - name: push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pdf
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
